version: '3'
services:
  gblockchain:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - APP_PORT=5000
        - TZ=Asia/Shanghai
    ports:
      - "5000:5000"
    environment:
      - APP_ENVIRONMENT=DEVELOPMENT
      - DEBUG=True
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql
    volumes:
      - logs-data:/logs:rw
    networks:
      - backend
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      disable: false
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mysql:
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=blockchain
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:3.2.11-alpine
    restart: always
    ports:
      - "6379"
    volumes:
      - db-data:/data:rw
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure


networks:
  backend:
    driver: bridge

volumes:
  logs-data:
  db-data:

